# Project info
sonar.organization=vws
sonar.projectKey=nl-rdo-zvs-web-private
sonar.projectName=nl-rdo-zvs-web-private

# Info links shown in SonarCloud
sonar.links.homepage=https://github.com/minvws/nl-rdo-zvs-web-private

# Source encoding
sonar.sourceEncoding=UTF-8

# Analysis scoping
sonar.sources=app
sonar.tests=tests

# Code coverage
sonar.php.tests.reportPath=reports/report-phpunit.xml
sonar.php.coverage.reportPaths=reports/coverage-phpunit.xml
sonar.coverage.exclusions=public/**/*,vendor/**/*,node_modules/**/*,app/Faker/**/*

# Additional reports
sonar.php.phpstan.reportPaths=reports/phpstan.json

# Duplication exclusions
sonar.cpd.exclusions=public/**/*,vendor/**/*,node_modules/**/*,app/**/*

# Language specific settings
sonar.issue.ignore.multicriteria=rule1,rule2,rule3
# Ignore unused method parameters in controllers
sonar.issue.ignore.multicriteria.rule1.ruleKey=php:S1172
sonar.issue.ignore.multicriteria.rule1.resourceKey=app/Http/Controllers/**/*
# Ignore too many methods in these classes
sonar.issue.ignore.multicriteria.rule2.ruleKey=php:S1448
sonar.issue.ignore.multicriteria.rule2.resourceKey=app/Models/Petition.php,app/ValueObjects/CalendarDate.php
# Ignore assertion methods without assertions
sonar.issue.ignore.multicriteria.rule3.ruleKey=php:S3699
sonar.issue.ignore.multicriteria.rule3.resourceKey=app/**/*

