ALTER TABLE "password_reset_tokens"
    ALTER COLUMN "created_at" TYPE TIMESTAMP(0) WITH TIME ZONE;

ALTER TABLE "personal_access_tokens"
    ALTER COLUMN "last_used_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "expires_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "created_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "updated_at" TYPE TIMESTAMP(0) WITH TIME ZONE;

ALTER TABLE "petition_exports"
    ALTER COLUMN "created_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "updated_at" TYPE TIMESTAMP(0) WITH TIME ZONE;

ALTER TABLE "petition_statuses_history_entries"
    ALTER COLUMN "created_at" TYPE TIMESTAMP(0) WITH TIME ZONE;

ALTER TABLE "users"
    ALTER COLUMN "email_verified_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "otp_verified_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "created_at" TYPE TIMESTAMP(0) WITH TIME ZONE,
    ALTER COLUMN "updated_at" TYPE TIMESTAMP(0) WITH TIME ZONE;
